# Generated by Django 4.0 on 2021-12-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('phonenumber', models.BigIntegerField(null=True)),
                ('gender', models.BooleanField(default=None)),
            ],
        ),
    ]
